### ISSUE TITLE
Ubuntu 16 support 

### ISSUE THREAD

**Issue by kurtuluso** [koding/kd#167]
When will it support ubuntu 6?

**Comment by sinan** [comment]
hi @kurtuluso this is the repo of our client side javascript framework probably you're talking about the `kd cli` right?

**Comment by kurtuluso** [comment]
That's right. I confused. I've encountered ubuntu upgrade need for kd cli.

10 Kas 2016 Per, saat 23:18 tarihinde Sinan Yasar <notifications@github.com>
şunu yazdı:
