### ISSUE TITLE
Support for touch events

### ISSUE THREAD

**Issue by austinkregel** [koding/kd#183]
I was curious to see if places where mouseup/mousedown is used, could it also allow for touchstart/touchend events for mobile users?

**Comment by sinan** [comment]
hi, mouseup/mousedown is by default [bound to the views](https://github.com/koding/kd/blob/master/lib/core/view.coffee#L17).

You can use it in one of the following ways.
```js
let view = new KDView({
  mousedown: (event) => {
    // your code to handle the event
  }
```
or if you extend the view
```js
class MyView extends KDView {
  mouseDown: (event) => {
    // your code before parent's mouseDown
    super(event)
    //your code after...
  }
}
```

As for the touchevents, since those are standard events but __not bound__ by default, you can do:

```js
let view = new KDView({
  bind: 'touchstart touchend',
  touchstart: event => { // your code },
  touchend: event => { // your code },
}) 
```

**Comment by austinkregel** [comment]
Okay, awesome :) Thanks!
